name: Regression Raspbian Node Version Updates(update-node)
run-name: Regression Raspbian against ${{ github.event.inputs.tag }}

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release/Branch/Tag'
        default: 'beta-4.51.2'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rpiImage: [ bullseye-run ]
        node-version: [18.18.2]

    steps:
    - uses: actions/checkout@v4
      name: Checkout ${{ github.repository }}@${{ github.event.inputs.tag }}
      with:
        ref: ${{ github.event.inputs.tag }}

    - uses: actions/setup-node@v3
      name: Setup NodeJS
      with:
        node-version: 18.x
        cache: 'npm'    

    - run: npm ci
    - run: npm run build:server
    - run: npm run lint:server
    - run: npm run test
    - run: npm pack

# TAG Image has been build

    - name: Linux - Setup Dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get --yes --no-install-recommends install binfmt-support qemu-user-static
        docker run --rm --privileged multiarch/qemu-user-static:register --reset

    - name: Linux - Build Docker Image
      if: runner.os == 'Linux'
      run: |
        docker build -f .github/Dockerfile --build-arg BASE_IMAGE=balenalib/raspberry-pi-debian:${{ matrix.rpiImage }} --build-arg QEMU_ARCH=${{ matrix.QEMU_ARCH }} -t raspbian .

    - name: Linux - Prebuild Binaries
      if: runner.os == 'Linux'
      run: |
        docker run --rm -v $(pwd):/node-pty raspbian
